### ISSUE TITLE
Approach

### ISSUE THREAD

**Issue by geftimov** [QVDev/DistilledViewPrefs#1]
First thanks for the library.
I have a question though :

Why you force to register a Shared Pref listener and in every change set different text size , font etc.
That way your Activity/Fragment/Presenter will be flooded with information about the changes for that TextView.

Can it be implemented by binding the dialog with the TextView and implement the changes inside.
Something like

```
DistilledPagePrefsView.showDialog(this,someTextView);
```

And in the dialog itself listen to the Shared pref changes and change the appearance of the TextView?

This is not an issue so you can close it when you want.

Thanks,
Georgi Eftimov

**Comment by QVDev** [comment]
Hi Georgi,

Good questions, let me try to explain them. 

Registering for the sharedpreferences is the most suitable in this situation I think. As the user wants to have this set for next time he enters the app. That being said it can probably be optimized by only saving it when leaving the dialog. 

As the showDialog is a static method, it would make the TextView also static. This is not something I would like. This was my first approach, and was far from optimal as I need to have the values stored on a global app level and should be restored when the user starts the app next time.

Regarding the flooding of the changes in the sharedpreferences, this is indeed something I am looking into. Such as on dialog closed or something like that. This for sure can be improved. But I think keeping the Shared Preferences make sense as I use it also as a user preference.

Thanks a lot for the feedback, feel free to contribute. I will update the library soon, as I have some thought of simplifying it, and minor improvements. If you have more suggestion please feel free to post them here and we see if we make an issue out of them. 

This we will keep, as for sure we can reduce the SharedPreferences calls?

Kind regards.

**Comment by QVDev** [comment]
@geftimov I have updated the library. See the README file for the new setup. I reduced some boilerplate for setting it up and listening for the shared prefs. Now less work is needed when you implement this.

**Comment by geftimov** [comment]
@QVDev 
Really nice job.

Thanks
